### ISSUE TITLE
Retroalimentació, semana 1

### ISSUE THREAD

**Issue by ccasasolam** [DancingAlien96/Web-server-in-C#1]
Muy buen trabajo. La funcionalidad y orden del código cumplen con el alcance de la primera semana. 
Te sugiero que, mientras se añade funcionalidad, dentro del while que escucha peticiones, agregues algo similar a esto:
sleep(3);
close(new_socket);

En el Makefile, te invito a sustituir el nombre del objeto salida y de los archivos .c de la línea:

$(CC) $(CFLAGS) -o servidor main.c lib/server_functions.c

por las variables automáticas adecuadas.

[ GNU Make – 7. Patrones y variables automáticas ](https://www.youtube.com/watch?v=h6cFvHNKimg)

**Comment by DancingAlien96** [comment]
ya se modifico aunque no de la manera mas optima

**Comment by ccasasolam** [comment]
Mejoró significativamente el makefile
